#include "semantic_fs/monitoring/i_file_system_view.h"
#include <windows.h>
namespace semantic_fs::monitoring { namespace {
std::optional<std::wstring> wide(std::string_view value) { const auto count = MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), nullptr, 0); if (!count) return std::nullopt; std::wstring result(count, L'\0'); return MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), result.data(), count) ? std::optional<std::wstring>(result) : std::nullopt; }
std::optional<std::string> utf8(std::wstring_view value) { const auto count = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), nullptr, 0, nullptr, nullptr); if (!count) return std::nullopt; std::string result(count, '\0'); return WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), result.data(), count, nullptr, nullptr) ? std::optional<std::string>(result) : std::nullopt; }
FsError failure(DWORD error) { return {error == ERROR_FILE_NOT_FOUND || error == ERROR_PATH_NOT_FOUND ? FsErrorCode::NotFound : error == ERROR_ACCESS_DENIED ? FsErrorCode::AccessDenied : FsErrorCode::Io}; }
class WindowsFileSystemView final : public IFileSystemView { public:
ListResult list(const AbsolutePath& directory) const override { const auto path = wide(directory.utf8); if (!path) return FsError{FsErrorCode::InvalidEncoding}; WIN32_FIND_DATAW data; const auto handle = FindFirstFileW(((*path) + L"\\*").c_str(), &data); if (handle == INVALID_HANDLE_VALUE) return failure(GetLastError()); std::vector<FileSystemEntry> result; do { const std::wstring_view name(data.cFileName); if (name == L"." || name == L"..") continue; const auto display = utf8(name); if (!display) { FindClose(handle); return FsError{FsErrorCode::InvalidEncoding}; } const auto attributes = data.dwFileAttributes; const auto kind = attributes & FILE_ATTRIBUTE_REPARSE_POINT ? FileSystemEntryKind::LinkOrReparse : attributes & FILE_ATTRIBUTE_DIRECTORY ? FileSystemEntryKind::Directory : FileSystemEntryKind::RegularFile; result.push_back({{directory.utf8 + "/" + *display}, kind}); } while (FindNextFileW(handle, &data)); const auto error = GetLastError(); FindClose(handle); return error == ERROR_NO_MORE_FILES ? ListResult{result} : ListResult{failure(error)}; }
MetadataResult metadata(const AbsolutePath& path) const override { const auto value = wide(path.utf8); if (!value) return FsError{FsErrorCode::InvalidEncoding}; WIN32_FILE_ATTRIBUTE_DATA data; if (!GetFileAttributesExW(value->c_str(), GetFileExInfoStandard, &data)) return failure(GetLastError()); return FileMetadata{(static_cast<std::uint64_t>(data.nFileSizeHigh) << 32) | data.nFileSizeLow, {}, {}}; }
}; }
std::unique_ptr<IFileSystemView> makeWindowsFileSystemView() { return std::make_unique<WindowsFileSystemView>(); }
} // namespace semantic_fs::monitoring