#include "semantic_fs/monitoring/i_path_semantics.h"
#include <windows.h>
namespace semantic_fs::monitoring { namespace {
std::optional<std::wstring> wide(std::string_view value) { const auto count = MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), nullptr, 0); if (!count) return std::nullopt; std::wstring result(count, L'\0'); return MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), result.data(), count) ? std::optional<std::wstring>(result) : std::nullopt; }
std::optional<std::string> utf8(const std::wstring& value) { const auto count = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), nullptr, 0, nullptr, nullptr); if (!count) return std::nullopt; std::string result(count, '\0'); return WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, value.data(), static_cast<int>(value.size()), result.data(), count, nullptr, nullptr) ? std::optional<std::string>(result) : std::nullopt; }
std::vector<std::string> parts(std::string_view path) { std::vector<std::string> result; std::string item; for (const char ch : path) { if (ch == '/' || ch == '\\') { if (!item.empty()) { result.push_back(item); item.clear(); } } else item += ch; } if (!item.empty()) result.push_back(item); return result; }
class WindowsPathSemantics final : public IPathSemantics { public:
std::optional<AbsolutePath> normalizeAbsolute(std::string_view value) const override { if (!isValidUtf8(value) || value.size() < 3 || value[1] != ':' || (value[2] != '/' && value[2] != '\\')) return std::nullopt; const auto source = wide(value); if (!source) return std::nullopt; const auto count = GetFullPathNameW(source->c_str(), 0, nullptr, nullptr); if (!count) return std::nullopt; std::wstring result(count, L'\0'); if (!GetFullPathNameW(source->c_str(), count, result.data(), nullptr)) return std::nullopt; result.resize(result.size() - 1); auto converted = utf8(result); if (!converted) return std::nullopt; for (char& ch : *converted) if (ch == '\\') ch = '/'; return AbsolutePath{*converted}; }
int compareComponent(std::string_view left, std::string_view right) const override { const auto lhs = wide(left), rhs = wide(right); if (!lhs || !rhs) return left == right ? 0 : left < right ? -1 : 1; return CompareStringOrdinal(lhs->data(), static_cast<int>(lhs->size()), rhs->data(), static_cast<int>(rhs->size()), TRUE) - CSTR_EQUAL; }
std::optional<RelativePath> relativeTo(const AbsolutePath& root, const AbsolutePath& candidate) const override { const auto normalizedRoot = normalizeAbsolute(root.utf8), normalizedCandidate = normalizeAbsolute(candidate.utf8); if (!normalizedRoot || !normalizedCandidate) return std::nullopt; const auto roots = parts(normalizedRoot->utf8), candidates = parts(normalizedCandidate->utf8); if (candidates.size() < roots.size()) return std::nullopt; for (std::size_t index = 0; index < roots.size(); ++index) if (compareComponent(roots[index], candidates[index]) != 0) return std::nullopt; std::vector<std::string> relative(candidates.begin() + static_cast<std::ptrdiff_t>(roots.size()), candidates.end()); std::string display; for (const auto& item : relative) display += (display.empty() ? "" : "/") + item; return RelativePath{display, relative}; }
}; }
std::unique_ptr<IPathSemantics> makeWindowsPathSemantics() { return std::make_unique<WindowsPathSemantics>(); }
} // namespace semantic_fs::monitoring