#include "semantic_fs/monitoring/i_catalog_outbox_writer.h"
#include "sqlite_migrations.h"

#include <sqlite3.h>
#include <stdexcept>

namespace semantic_fs::monitoring {
namespace {
std::string join(const RelativePath& path) { std::string result; for (const auto& component : path.components) { result.push_back('\x1f'); result += component; } return result; }
bool samePath(const IPathSemantics& paths, std::string_view stored, const RelativePath& current) { if (stored.empty() || stored.front() != '\x1f') return false; std::size_t start = 1, index = 0; while (start <= stored.size() && index < current.components.size()) { const auto end = stored.find('\x1f', start); if (paths.compareComponent(stored.substr(start, end == std::string_view::npos ? stored.size() - start : end - start), current.components[index++]) != 0) return false; if (end == std::string_view::npos) return index == current.components.size(); start = end + 1; } return false; }
bool validPath(const NormalizedPath& path) { if (!isValidUtf8(path.displayUtf8) || !isValidUtf8(path.relative.utf8)) return false; for (const auto& component : path.relative.components) if (!isValidUtf8(component)) return false; return !path.relative.components.empty(); }
class Writer final : public ICatalogOutboxWriter {
public:
    Writer(const std::filesystem::path& path, const IPathSemantics& paths, IIdSource& ids, const CatalogOutboxConfig& config) : database_(path.string().c_str()), paths_(paths), ids_(ids), config_(config) { if (config_.schemaVersion != kFileChangeSchemaVersion) throw std::runtime_error("unsupported file schema"); storage::runCatalogOutboxMigrations(database_, config_.migrationChecksum); database_.exec("PRAGMA busy_timeout=" + std::to_string(config_.busyTimeoutMilliseconds)); }
    MutationResult apply(const TransitionCommand& command) override {
        if ((command.kind != ChangeKind::Discovered && command.kind != ChangeKind::Created && command.kind != ChangeKind::Modified) || !validPath(command.path)) return {MutationStatus::Invalid, {}, {}};
        try { database_.exec("BEGIN IMMEDIATE"); sqlite3_stmt* watermark = nullptr; sqlite3_prepare_v2(database_.get(), "INSERT INTO store_runtime(singleton,last_seen_utc) VALUES(1,?) ON CONFLICT(singleton) DO UPDATE SET last_seen_utc=max(last_seen_utc,excluded.last_seen_utc)", -1, &watermark, nullptr); sqlite3_bind_int64(watermark, 1, static_cast<sqlite3_int64>(command.observedAt.microsecondsSinceEpoch)); if (sqlite3_step(watermark) != SQLITE_DONE) throw std::runtime_error("watermark write failed"); sqlite3_finalize(watermark); sqlite3_stmt* find = nullptr; sqlite3_prepare_v2(database_.get(), "SELECT observation_id,path,generation,size FROM observed_files WHERE root_id=?", -1, &find, nullptr); sqlite3_bind_text(find, 1, command.rootId.value().data(), -1, SQLITE_TRANSIENT);
            std::string observation; std::uint64_t generation = 0; std::optional<std::uint64_t> size; while (sqlite3_step(find) == SQLITE_ROW) { const auto path = reinterpret_cast<const char*>(sqlite3_column_text(find, 1)); if (samePath(paths_, path, command.path.relative)) { observation = reinterpret_cast<const char*>(sqlite3_column_text(find, 0)); generation = static_cast<std::uint64_t>(sqlite3_column_int64(find, 2)); if (sqlite3_column_type(find, 3) != SQLITE_NULL) size = static_cast<std::uint64_t>(sqlite3_column_int64(find, 3)); break; } } sqlite3_finalize(find);
            if (command.expectedGeneration && command.expectedGeneration->value != generation) { database_.exec("ROLLBACK"); return {MutationStatus::Invalid, {}, {}}; }
            if (!observation.empty() && size == command.metadata.size) { database_.exec("ROLLBACK"); return {MutationStatus::Equivalent, {}, Generation{generation}}; }
            const bool isNew = observation.empty(); if (isNew) observation = ids_.nextObservationId(); const auto event = ids_.nextEventId(); const auto next = generation + 1; if (!ObservationId::create(observation) || !EventId::create(event)) { database_.exec("ROLLBACK"); return {MutationStatus::Invalid, {}, {}}; }
            sqlite3_stmt* write = nullptr; const char* sql = isNew ? "INSERT INTO observed_files(observation_id,root_id,path,generation,size) VALUES(?,?,?,?,?)" : "UPDATE observed_files SET generation=?,size=? WHERE observation_id=?"; sqlite3_prepare_v2(database_.get(), sql, -1, &write, nullptr); int bind = 1; if (isNew) { sqlite3_bind_text(write, bind++, observation.c_str(), -1, SQLITE_TRANSIENT); sqlite3_bind_text(write, bind++, command.rootId.value().data(), -1, SQLITE_TRANSIENT); const auto path = join(command.path.relative); sqlite3_bind_text(write, bind++, path.c_str(), -1, SQLITE_TRANSIENT); } sqlite3_bind_int64(write, bind++, static_cast<sqlite3_int64>(next)); if (command.metadata.size) sqlite3_bind_int64(write, bind++, static_cast<sqlite3_int64>(*command.metadata.size)); else sqlite3_bind_null(write, bind++); if (!isNew) sqlite3_bind_text(write, bind++, observation.c_str(), -1, SQLITE_TRANSIENT); if (sqlite3_step(write) != SQLITE_DONE) { sqlite3_finalize(write); throw std::runtime_error("catalog write failed"); } sqlite3_finalize(write);
            const auto payload = command.path.displayUtf8; sqlite3_prepare_v2(database_.get(), "INSERT INTO event_outbox(event_id,observation_id,generation,schema_version,payload,state) VALUES(?,?,?,?,?, 'pending')", -1, &write, nullptr); sqlite3_bind_text(write, 1, event.c_str(), -1, SQLITE_TRANSIENT); sqlite3_bind_text(write, 2, observation.c_str(), -1, SQLITE_TRANSIENT); sqlite3_bind_int64(write, 3, static_cast<sqlite3_int64>(next)); sqlite3_bind_int(write, 4, static_cast<int>(kFileChangeSchemaVersion)); sqlite3_bind_text(write, 5, payload.c_str(), -1, SQLITE_TRANSIENT); if (sqlite3_step(write) != SQLITE_DONE) { sqlite3_finalize(write); throw std::runtime_error("outbox write failed"); } sqlite3_finalize(write);
            const auto pending = pendingEventCount(); if ((config_.hardPendingRows && pending > config_.hardPendingRows) || (config_.hardPayloadBytes && payload.size() > config_.hardPayloadBytes)) { database_.exec("ROLLBACK"); return {MutationStatus::HardLimited, {}, {}}; } if (config_.failpoint == CatalogOutboxFailpoint::BeforeCommit) { database_.exec("ROLLBACK"); return {MutationStatus::StorageFailure, {}, {}}; } const bool soft = config_.softPendingRows && pending > config_.softPendingRows; database_.exec("COMMIT"); if (config_.failpoint == CatalogOutboxFailpoint::AfterCommit) return {MutationStatus::StorageFailure, {}, {}}; return {soft ? MutationStatus::SoftLimited : MutationStatus::Applied, EventId::create(event), Generation{next}};
        } catch (...) { try { database_.exec("ROLLBACK"); } catch (...) {} return {MutationStatus::StorageFailure, {}, {}}; }
    }
    CoverageResult recordCoverage(const CoverageCommand& command) override { try { database_.exec("BEGIN IMMEDIATE"); sqlite3_stmt* statement = nullptr; sqlite3_prepare_v2(database_.get(), "INSERT INTO dirty_obligations(root_id,epoch,reasons) VALUES(?,?,?) ON CONFLICT(root_id) DO UPDATE SET epoch=max(epoch,excluded.epoch),reasons=(reasons|excluded.reasons)", -1, &statement, nullptr); sqlite3_bind_text(statement,1,command.rootId.value().data(),-1,SQLITE_TRANSIENT); sqlite3_bind_int64(statement,2,static_cast<sqlite3_int64>(command.epoch)); sqlite3_bind_int(statement,3,static_cast<int>(command.reasons)); if (sqlite3_step(statement)!=SQLITE_DONE) throw std::runtime_error("dirty obligation failed"); sqlite3_finalize(statement); if (command.deferredKind) { const auto kind=*command.deferredKind==ChangeKind::Removed?"removed":*command.deferredKind==ChangeKind::Renamed?"renamed":""; if (!*kind) { database_.exec("ROLLBACK"); return {CoverageStatus::Refused}; } sqlite3_prepare_v2(database_.get(),"INSERT INTO deferred_coverage(root_id,kind) VALUES(?,?)",-1,&statement,nullptr); sqlite3_bind_text(statement,1,command.rootId.value().data(),-1,SQLITE_TRANSIENT); sqlite3_bind_text(statement,2,kind,-1,SQLITE_STATIC); if(sqlite3_step(statement)!=SQLITE_DONE) throw std::runtime_error("deferred evidence failed"); sqlite3_finalize(statement); } database_.exec("COMMIT"); return {command.deferredKind?CoverageStatus::Deferred:CoverageStatus::Persisted}; } catch (...) { try { database_.exec("ROLLBACK"); } catch (...) {} return {CoverageStatus::StorageFailure}; } }
    std::size_t pendingEventCount() const override { sqlite3_stmt* statement = nullptr; sqlite3_prepare_v2(database_.get(), "SELECT count(*) FROM event_outbox WHERE state='pending'", -1, &statement, nullptr); const auto count = sqlite3_step(statement) == SQLITE_ROW ? static_cast<std::size_t>(sqlite3_column_int64(statement, 0)) : 0; sqlite3_finalize(statement); return count; }
    UtcTimestamp lastSeenUtc() const override { sqlite3_stmt* statement=nullptr; sqlite3_prepare_v2(database_.get(),"SELECT last_seen_utc FROM store_runtime WHERE singleton=1",-1,&statement,nullptr); const auto value=sqlite3_step(statement)==SQLITE_ROW?sqlite3_column_int64(statement,0):0; sqlite3_finalize(statement); return {value}; }
    std::uint32_t dirtyReasonCount(const RootId& root) const override { sqlite3_stmt* statement=nullptr; sqlite3_prepare_v2(database_.get(),"SELECT reasons FROM dirty_obligations WHERE root_id=?",-1,&statement,nullptr); sqlite3_bind_text(statement,1,root.value().data(),-1,SQLITE_TRANSIENT); const auto value=sqlite3_step(statement)==SQLITE_ROW?static_cast<std::uint32_t>(sqlite3_column_int(statement,0)):0; sqlite3_finalize(statement); return value; }
    std::size_t deferredEvidenceCount() const override { sqlite3_stmt* statement=nullptr; sqlite3_prepare_v2(database_.get(),"SELECT count(*) FROM deferred_coverage",-1,&statement,nullptr); const auto value=sqlite3_step(statement)==SQLITE_ROW?static_cast<std::size_t>(sqlite3_column_int64(statement,0)):0; sqlite3_finalize(statement); return value; }
    std::optional<Generation> generationFor(const RootId& root, const NormalizedPath& path) const override { sqlite3_stmt* statement = nullptr; sqlite3_prepare_v2(database_.get(), "SELECT path,generation FROM observed_files WHERE root_id=?", -1, &statement, nullptr); sqlite3_bind_text(statement, 1, root.value().data(), -1, SQLITE_TRANSIENT); while (sqlite3_step(statement) == SQLITE_ROW) if (samePath(paths_, reinterpret_cast<const char*>(sqlite3_column_text(statement, 0)), path.relative)) { const auto value = Generation::create(static_cast<std::uint64_t>(sqlite3_column_int64(statement, 1))); sqlite3_finalize(statement); return value; } sqlite3_finalize(statement); return {}; }
private: storage::SqliteDatabase database_; const IPathSemantics& paths_; IIdSource& ids_; CatalogOutboxConfig config_;
};
}
std::unique_ptr<ICatalogOutboxWriter> openSqliteCatalogOutbox(const std::filesystem::path& path, const IPathSemantics& paths, IIdSource& ids, const CatalogOutboxConfig& config) { return std::make_unique<Writer>(path, paths, ids, config); }
} // namespace semantic_fs::monitoring
