#include "sqlite_migrations.h"
#include <stdexcept>
namespace semantic_fs::storage {
void runCatalogOutboxMigrations(const SqliteDatabase& database, std::string_view checksum) {
    if (checksum != "catalog-outbox-v3") throw std::runtime_error("unsupported migration checksum");
    database.exec("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA synchronous=FULL; PRAGMA busy_timeout=2500; BEGIN IMMEDIATE; CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, checksum TEXT NOT NULL); CREATE TABLE IF NOT EXISTS store_runtime(singleton INTEGER PRIMARY KEY CHECK(singleton=1),last_seen_utc INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS observed_files(observation_id TEXT PRIMARY KEY, root_id TEXT NOT NULL, path TEXT NOT NULL, generation INTEGER NOT NULL CHECK(generation>0), size INTEGER, modified_at INTEGER); CREATE TABLE IF NOT EXISTS event_outbox(event_id TEXT PRIMARY KEY, observation_id TEXT NOT NULL, generation INTEGER NOT NULL, payload TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('pending','leased','delivered','terminal')), FOREIGN KEY(observation_id) REFERENCES observed_files(observation_id)); CREATE TABLE IF NOT EXISTS dirty_obligations(root_id TEXT PRIMARY KEY,epoch INTEGER NOT NULL,reasons INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS deferred_coverage(id INTEGER PRIMARY KEY,root_id TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('removed','renamed')));");
    sqlite3_stmt* statement = nullptr; sqlite3_prepare_v2(database.get(), "SELECT max(version) FROM schema_migrations", -1, &statement, nullptr); if (sqlite3_step(statement) == SQLITE_ROW && sqlite3_column_type(statement, 0) != SQLITE_NULL && sqlite3_column_int(statement, 0) > 3) { sqlite3_finalize(statement); database.exec("ROLLBACK"); throw std::runtime_error("unsupported migration version"); } sqlite3_finalize(statement); sqlite3_prepare_v2(database.get(), "SELECT checksum FROM schema_migrations WHERE version=1", -1, &statement, nullptr);
    int result = sqlite3_step(statement); if (result == SQLITE_ROW && std::string_view(reinterpret_cast<const char*>(sqlite3_column_text(statement, 0))) != "catalog-outbox-v1") { sqlite3_finalize(statement); database.exec("ROLLBACK"); throw std::runtime_error("migration checksum drift"); } sqlite3_finalize(statement); database.exec("INSERT OR IGNORE INTO schema_migrations(version,checksum) VALUES(1,'catalog-outbox-v1');");
    sqlite3_prepare_v2(database.get(), "SELECT checksum FROM schema_migrations WHERE version=2", -1, &statement, nullptr); result = sqlite3_step(statement); if (result == SQLITE_ROW && std::string_view(reinterpret_cast<const char*>(sqlite3_column_text(statement, 0))) != "catalog-outbox-v2") { sqlite3_finalize(statement); database.exec("ROLLBACK"); throw std::runtime_error("migration checksum drift"); } sqlite3_finalize(statement); if (result != SQLITE_ROW) database.exec("ALTER TABLE event_outbox ADD COLUMN schema_version INTEGER NOT NULL DEFAULT 1; INSERT INTO schema_migrations(version,checksum) VALUES(2,'catalog-outbox-v2');");
    sqlite3_prepare_v2(database.get(), "SELECT checksum FROM schema_migrations WHERE version=3", -1, &statement, nullptr); result = sqlite3_step(statement); if (result == SQLITE_ROW && std::string_view(reinterpret_cast<const char*>(sqlite3_column_text(statement, 0))) != checksum) { sqlite3_finalize(statement); database.exec("ROLLBACK"); throw std::runtime_error("migration checksum drift"); } sqlite3_finalize(statement); if (result != SQLITE_ROW) database.exec("ALTER TABLE event_outbox ADD COLUMN available_at INTEGER NOT NULL DEFAULT 0; ALTER TABLE event_outbox ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0; ALTER TABLE event_outbox ADD COLUMN lease_owner TEXT; ALTER TABLE event_outbox ADD COLUMN lease_token TEXT; ALTER TABLE event_outbox ADD COLUMN lease_deadline INTEGER; ALTER TABLE event_outbox ADD COLUMN diagnostic TEXT; ALTER TABLE event_outbox ADD COLUMN kind TEXT NOT NULL DEFAULT 'created'; ALTER TABLE event_outbox ADD COLUMN observed_at INTEGER NOT NULL DEFAULT 0; ALTER TABLE event_outbox ADD COLUMN source INTEGER NOT NULL DEFAULT 0; INSERT INTO schema_migrations(version,checksum) VALUES(3,'catalog-outbox-v3');"); database.exec("COMMIT;");
}
} // namespace semantic_fs::storage
